source 'http://rubygems.org'

gem 'nokogiri'
gem 'json'

# push notifications
gem 'apns' # apple push notification service
gem 'wpns' # WP7 push notification service
gem 'c2dm' # Andoid push notification (or call it cloud to device messaging if you're the business guy)

# persistence
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-transactions'
gem 'dm-validations'
gem 'dm-sqlite-adapter'

# for the tests
gem 'rspec', '=2.7'
