source 'http://rubygems.org'

# geocoding, map location calculations, ...
gem 'geokit'
gem 'json_pure' # required by geokit

# push notifications
gem 'apns' # apple push notification service
gem 'wpns' # WP7 push notification service

# persistence
gem 'dm-core'
gem 'dm-migrations'
gem 'dm-transactions'
gem 'dm-validations'
gem 'dm-sqlite-adapter'

# for the tests
gem 'rspec', '=2.7'
